library(car)
library(effectsize)
# Load package
library(readxl)
Ovent2<-read_excel("~/path/Supplemenatry_data_data_set_for_analyses.xlsx", sheet = "Sheet1")
names(Ovent2)

#Analyses for Table 2 and MANOVA
names(Ovent2)

#
library(nlme)
model701<-lme(Sperm_longevity~ERFM+log(BD)+CSR, random=~1|Name, method="ML", data=Ovent2)
summary(model701)
anova(model701)
Anova(model701, type=c("II"), test.statistic=c("Chisq") )

#analyses for Table 2
library(effectsize)
model501<-lm(Sperm_longevity~ERFM+log(BD)+CSR, data=Ovent2)
summary(model501)
Anova(model501, type=c("II"), test.statistic=c("F") )
eta_squared(car::Anova(model501, type = 2), partial = FALSE)
model502<-lm(Sperm_Swimming_velocity_10sec~ERFM+log(BD)+CSR, data=Ovent2)
summary(model502)
Anova(model502, type=c("II"), test.statistic=c("F") )
eta_squared(car::Anova(model502, type = 2), partial = FALSE)
model503<-lm(LogRelativeSPP120_pseud~ERFM+log(BD)+CSR, data=Ovent2)
summary(model503)
Anova(model503, type=c("II"), test.statistic=c("F") )
eta_squared(car::Anova(model503, type = 2), partial = FALSE)
model504<-lm(Log_RelativeSPP_1~ERFM+log(BD)+CSR, data=Ovent2)
summary(model504)
Anova(model504, type=c("II"), test.statistic=c("F") )
eta_squared(car::Anova(model504, type = 2), partial = FALSE)
model505<-lm(log(testes)~ERFM+log(BD)+CSR+LogSM, data=Ovent2)
summary(model505)
Anova(model505, type=c("II"), test.statistic=c("F") )
eta_squared(car::Anova(model505, type = 2), partial = FALSE)

model506<-lm(Sperm_longevity~Sperm_Swimming_velocity_10sec, data=Ovent2)
summary(model506)
Anova(model506, type=c("II"), test.statistic=c("F") )
eta_squared(car::Anova(model506, type = 2), partial = FALSE)

#analyses for supplementary table 5
model507<-lm(Sperm_longevity_80per~ERFM+log(DS)+CSR, data=Ovent2)
summary(model507)
Anova(model507, type=c("II"), test.statistic=c("F") )
eta_squared(car::Anova(model507, type = 2), partial = FALSE)


#MANOVA for supplementary statistics 1
model507<-manova(cbind(Ovent2$Sperm_longevity, Ovent2$Sperm_Swimming_velocity_10sec, Ovent2$LogRelativeSPP120_pseud, Ovent2$Log_RelativeSPP_1, Ovent2$LogGM)~ERFM+log(BD)+CSR+LogSM, data=Ovent2)
summary(model507)
summary.aov(model507)
Anova(model507, type=c("II"))
eta_squared(car::Anova(model507, type = 2), partial = FALSE)


## relationship between spawning success and traits, including Fluton K
model101<-glm(Spawned~ERFM+log(BD)+Sperm_longevity+CSR+Sperm_Swimming_velocity_10sec+LogRelativeSPP120_pseud+Log_RelativeSPP_1+log(testes)+LogSM+K, family=binomial, data=Ovent2)
summary(model101)
step(model101)
model102<-glm(Spawned~ERFM+log(BD)+Sperm_longevity+CSR+Sperm_Swimming_velocity_10sec+LogRelativeSPP120_pseud+Log_RelativeSPP_1+K, family=binomial, data=Ovent2)
model103<-glm(Spawned~ERFM+log(BD)+Sperm_longevity+CSR+Sperm_Swimming_velocity_10sec+LogRelativeSPP120_pseud+log(testes)+LogSM+K, family=binomial, data=Ovent2)
model104<-glm(Spawned~log(BD)+Log_RelativeSPP_1+log(testes)+LogSM+K, family=binomial, data=Ovent2)
summary(model101)
summary(model102)
summary(model103)
summary(model104)
step(model102)
step(model103)
Anova(model102, type=c("II"), test.statistic=c("LR"), )
Anova(model103, type=c("II"), test.statistic=c("LR"), )

model102_dry<-glm(Spawned~ERFM+log(BD)+Sperm_longevity+CSR+Sperm_Swimming_velocity_10sec+LogRelativeSPP120_pseud+Log_RelativeSPP_1+K_dry, family=binomial, data=Ovent2)
model103_dry<-glm(Spawned~ERFM+log(BD)+Sperm_longevity+CSR+Sperm_Swimming_velocity_10sec+LogRelativeSPP120_pseud+log(testes)+LogSM+K_dry, family=binomial, data=Ovent2)
model104_dry<-glm(Spawned~log(BD)+Log_RelativeSPP_1+log(testes)+LogSM+K_dry, family=binomial, data=Ovent2)
model105_dry<-glm(Spawned~Log_RelativeSPP_1+K_dry, family=binomial, data=Ovent2)
summary(model102_dry)
summary(model103_dry)
summary(model104_dry)
summary(model105_dry)
step(model102_dry)
step(model103_dry)
Anova(model102_dry, type=c("II"), test.statistic=c("LR"), )
Anova(model103_dry, type=c("II"), test.statistic=c("LR"), )
Anova(model104_dry, type=c("II"), test.statistic=c("LR"), )
Anova(model105_dry, type=c("II"), test.statistic=c("LR"), )

model11<-glm(Spawned~Log_RelativeSPP_1+K, family=binomial, data=Ovent2)
summary(model11)
Anova(model11, type=c("II"), test.statistic=c("LR"))
anova(model11, model08, test="Chi")
anova(model11, model10, test="Chi")
model112<-glm(Spawned~ERFM+Sperm_Swimming_velocity_10sec+Log_RelativeSPP_1+K, family=binomial, data=Ovent2)
summary(model112)
model132<-glm(Spawned~ERFM+Log_RelativeSPP_1+K, family=binomial, data=Ovent2)
summary(model132)
model132<-glm(Spawned~Log_RelativeSPP_1+K, family=binomial, data=Ovent2)
summary(model132)
Anova(model132, type=c("II"), test.statistic=c("LR"), )
eta_squared(model132, partial=TRUE)

model138<-glm(Spawned~Log_RelativeSPP_1+K_dry, family=binomial, data=Ovent2)
summary(model138)
Anova(model138, type=c("II"), test.statistic=c("LR"), )
eta_squared(model138, partial=TRUE)

model139<-glm(Spawned~Log_RelativeSPP_1, family=binomial, data=Ovent2)
summary(model139)
Anova(model139, type=c("II"), test.statistic=c("LR"), )
eta_squared(model139, partial=TRUE)
